export const Descriptions = [
    'A Southern classic, this dish features a crispy breaded steak topped with a rich, creamy processed cheese sauce. It’s a hearty meal that combines the crunch of fried chicken with the indulgence of melted cheese.',
    'This comfort food staple consists of a tender steak that’s breaded and fried until golden, often served with country gravy. It’s a filling dish that’s synonymous with Southern hospitality.',
    'Juicy grilled beef steaks are smothered in a savory mushroom sauce, bringing earthy flavors to the forefront. This dish is a testament to the timeless pairing of beef and mushrooms.',
    'Perfectly cooked pork chops are complemented by a sweet and tangy apple sauce, creating a delightful contrast of flavors. The apple sauce adds a fruity twist to the succulent pork.',
    'This elegant entrée features a tender beef tenderloin accompanied by sweet roasted peppers and onions. The vegetables add a colorful and flavorful dimension to the rich beef.',
    'A luxurious cut of filet mignon is wrapped in bacon and topped with melted cheese, combining three beloved flavors in one exquisite dish. It’s a decadent choice for a special occasion.',
    'Oven-baked salmon fillets are enhanced with a lemon-herb butter, melting into the fish for a moist and flavorful experience. The citrus and herbs bring a light freshness to the rich salmon.',
    'This dish offers the smoky char of grilled salmon paired with a zesty lemon-herb butter that complements the fish’s natural flavors. It’s a healthy yet flavorful option for seafood lovers.',
    'Succulent shrimp are marinated in a lemon garlic sauce and grilled to perfection. They’re bursting with bright, tangy flavors that are sure to tantalize the taste buds.',
    'A whole chicken is roasted until the skin is crispy and golden, then basted with a lemon-herb butter for added moisture and flavor. It’s a comforting and aromatic meal that’s perfect for family dinners.',
    'The filet mignon is roasted to tender perfection and finished with a lemon-herb butter that melts over the meat, infusing it with subtle citrus notes. It’s an elegant dish that’s simple yet sophisticated.',
    'The salmon is slow-roasted to enhance its natural oils and flavors, then topped with a lemon-herb butter that adds a bright and aromatic finish. It’s a dish that showcases the delicate taste of salmon.',

    ' A classic comfort food, these mashed potatoes are infused with the rich, savory taste of garlic. They’re whipped to a smooth, velvety texture that’s perfect for soaking up gravy or sauce.',
    'This dish features fresh asparagus stalks grilled until crisp-tender and then enhanced with a tangy lemon butter sauce. It’s a light, refreshing side that pairs well with any main course.',
    ' Sweet corn is elevated with a dollop of butter mixed with finely chopped herbs, offering a fragrant twist to this summertime favorite. The herbs complement the natural sweetness of the corn, making it a hit at any barbecue.',
    'A gooey, cheesy delight, this baked macaroni and cheese is a crowd-pleaser with its golden-brown breadcrumb topping. It’s the ultimate comfort dish, with layers of pasta and cheese baked to perfection.',
    'Roasted until golden and crispy, these Brussels sprouts are mixed with savory bacon bits. The combination of the vegetable’s slight bitterness with the smoky bacon flavor makes for a mouthwatering side.',
    'These carrots are glazed in a sweet honey sauce that caramelizes in the oven, bringing out the natural sweetness of the vegetable. They’re a simple yet elegant side dish that adds a pop of color and flavor to the table.',
    'A luxurious take on the classic French fry, these are tossed with truffle oil and grated Parmesan cheese. They’re indulgent and aromatic, with a rich flavor that’s hard to resist.',
    'This creamy spinach dish is a decadent way to enjoy your greens, with a rich béchamel sauce and a hint of nutmeg. It’s a comforting side that’s both rich and satisfying.',
    'Crisp green beans sautéed to perfection and sprinkled with toasted almonds. This dish offers a delightful crunch and nutty flavor that complements the beans’ freshness.',
    'Bell peppers filled with a savory mixture of rice, meat, and spices, then baked until the peppers are tender. They serve as a colorful and hearty dish that can stand alone as a main or a substantial side.',

    "Indulge in the timeless elegance of our Classic Caesar Salad, where crisp romaine is adorned with aged Parmesan, crunchy croutons, and our rich, anchovy-infused dressing. It's a beloved classic redefined with gourmet flair.",
    "Experience the Mediterranean in a bowl with our Greek Salad with Feta Cheese, bursting with juicy tomatoes, crisp cucumbers, and tangy olives, all brought together by the creamy richness of feta cheese. It's a refreshing journey to the sunny Aegean coast.",
    "Delight in the sweet and savory harmony of our Spinach and Strawberry Salad, a blend of tender baby spinach and ripe strawberries, accented with toasted almonds and a poppy seed dressing. It's a vibrant celebration of flavors and textures.",
    "Savor the hearty goodness of our Cobb Salad with Avocado, a robust combination of grilled chicken, crispy bacon, and ripe avocado, topped with a medley of eggs, blue cheese, and fresh greens. It's a satisfying meal in every forkful.",
    'Embark on a healthful adventure with our Quinoa Salad with Roasted Vegetables, featuring fluffy quinoa and a colorful array of roasted seasonal veggies. A light lemon dressing adds zest to this nutritious and delicious dish.',
    'Relish the simple beauty of our Caprese Salad with Balsamic Glaze, where slices of ripe tomatoes and fresh mozzarella meet the sweet tang of balsamic reduction. Fresh basil leaves add a fragrant touch to this Italian favorite.',
    "Dive into the exotic flavors of our Asian Chicken Salad with Sesame Dressing, a crisp mix of cabbage, carrots, and chicken, tossed in a zesty sesame dressing and topped with crunchy wonton strips. It's a fusion of taste that's sure to delight.",
    "Enjoy the earthy elegance of our Beetroot and Goat Cheese Salad, a colorful mélange of roasted beets, creamy goat cheese, and candied walnuts, all drizzled with a honey vinaigrette. It's a gourmet twist on rustic ingredients.",
    "Get whisked away to the Southwest with our Southwest Salad with Cilantro Lime Dressing, a lively blend of black beans, corn, and peppers, dressed in a vibrant cilantro lime vinaigrette. It's a fiesta of flavors in every bite.",
    "Embrace the wholesome goodness of our Kale Salad with Lemon Vinaigrette, where curly kale is massaged with a zesty lemon dressing and sprinkled with sunflower seeds and dried cranberries. It's a superfood feast that's both nourishing and delicious.",
    
    // desserts
    "Classic New York Cheesecake: Dive into the creamy, dreamy world of our Classic New York Cheesecake, a velvety smooth delight with a buttery graham cracker crust. It's the epitome of indulgence, a perfect balance of tangy and sweet.",
    "Chocolate Lava Cake with Vanilla Ice Cream: Experience the eruption of flavor with our Chocolate Lava Cake, where warm, molten chocolate heart meets cool vanilla ice cream. It's a decadent dance of hot and cold, rich and refreshing.",
    "Apple Pie with Cinnamon: Our Apple Pie is a slice of heaven, brimming with tender, spiced apples and encased in a flaky, golden crust. A dusting of cinnamon adds the final touch to this timeless classic.",
    "Tiramisu with Mascarpone Cream: Savor the layers of our Tiramisu, where espresso-soaked ladyfingers and luscious mascarpone cream converge. It's a luxurious journey through texture and taste, topped with a dusting of cocoa.",
    "Lemon Tart with Raspberry Sauce: Brighten your palate with our Lemon Tart, a zesty creation with a crisp pastry shell. The sweet-tart raspberry sauce complements the filling, creating a refreshing and vibrant dessert.",
    "Crème Brûlée with Fresh Berries: Indulge in the delicate crunch of our Crème Brûlée's caramelized sugar top, giving way to a silky custard beneath. Fresh berries add a juicy burst of flavor to this elegant dessert.",
    "Red Velvet Cake with Cream Cheese Frosting: Fall in love with our Red Velvet Cake, a dramatic display of deep red sponge and creamy white frosting. Each bite is a tender, tangy, and utterly irresistible treat.",
    "Brownie Sundae with Hot Fudge: Delight in our Brownie Sundae, a warm, gooey brownie paired with cold, creamy ice cream. Drizzled with hot fudge, it's a textural masterpiece that's both comforting and luxurious.",
    'Panna Cotta with Mixed Berry Compote: Discover the silky-smooth perfection of our Panna Cotta, a light and creamy dessert. The mixed berry compote adds a touch of sweetness and a pop of color, making it a feast for the senses.',
    "Bread Pudding with Bourbon Sauce: Embrace the warmth of our Bread Pudding, a cozy blend of soft, spiced bread and rich, velvety bourbon sauce. It's a comforting end to any meal, steeped in tradition and flavor.",

    //strong alcohol
    'A clear, distilled spirit of Russian origin that’s smooth and often enjoyed neat or as a versatile cocktail base.',
    'A rich, amber-hued spirit known for its complex flavors that range from sweet to smoky, aged in wooden casks.',
    'A sweet and sometimes spiced spirit distilled from sugarcane byproducts, perfect for tropical drinks.',
    'A bold Mexican spirit made from blue agave, often sipped slowly or mixed in margaritas.',
    'A smoky and robust spirit also derived from agave, offering a deeper flavor profile than tequila.',
    'Not commonly recognized as a standalone drink, but likely a misspelling of ‘mezcal’ or a reference to the mesquite plant used for flavoring.',
    'A Japanese distilled beverage typically made from barley, sweet potatoes, or rice, with a light, clean taste.',
    'A juniper-flavored spirit that’s the cornerstone of many classic cocktails, known for its herbal and floral notes.',
    'A colorful cocktail made with tequila, orange juice, and grenadine, symbolizing a sunrise in a glass.',
    'A type of brandy from the Cognac region of France, celebrated for its rich, smooth texture and aging process.',
    'An iconic cocktail made with gin (or vodka) and vermouth, often garnished with an olive or a lemon twist.',

    //light alcohol
    'A robust wine with a complex bouquet of flavors, often featuring notes of dark fruits and a tannic finish.',
    'A more approachable red with a balance of fruitiness and dryness, suitable for a variety of palates.',
    'A crisp and refreshing wine with subtle flavors of berries and a clean, dry finish.',
    'This rosé offers a touch of sweetness, making it a delightful choice for those who enjoy a fruit-forward wine.',
    'A light and zesty wine that may exhibit citrus or green apple notes, perfect for pairing with seafood.',
    'With a hint of sweetness, this white wine is versatile and can complement both sweet and savory dishes.',
    'The quintessential celebratory drink, known for its effervescence and elegance.',
    'An Italian sparkling wine that’s refreshingly light and often enjoyed as an aperitif.',
    'A fruity beverage made from fermented apple juice, ranging from sweet to dry.',
    'A pale, refreshing brew with a smooth taste and a clean finish, often lower in alcohol content.',
    'A rich, full-bodied beer with deep malt flavors and notes of caramel or chocolate.',
    'A Japanese rice wine that’s smooth and can be enjoyed warm or chilled, often with a delicate umami flavor.',
    'A popular Korean spirit with a clean taste and a subtle sweetness, typically consumed neat.',

    //alcoholic cocktails
    'A refreshing cocktail made with tequila, lime juice, and triple sec, often served with salt on the rim of the glass.',
    'A Cuban classic consisting of white rum, sugar, lime juice, soda water, and mint, creating a light and invigorating mix.',
    'A traditional American cocktail featuring bourbon or rye whiskey, sugar, water, and bitters, garnished with an orange slice or zest.',
    'A sophisticated blend of whiskey, sweet vermouth, and bitters, typically garnished with a cherry.',
    'A chic, tart drink made with vodka, triple sec, cranberry juice, and freshly squeezed or sweetened lime juice.',
    'A simple yet potent cocktail composed of rum, citrus juice (usually lime), and sugar.',
    'A fizzy and refreshing mix of gin, lemon juice, sugar, and carbonated water, served in a tall glass.',
    'A zesty cocktail made with vodka, spicy ginger beer, and lime juice, served in a distinctive copper mug.',
    'A smooth combination of whiskey, lemon juice, and sugar, with an optional dash of egg white for a frothy top.',
    'A sharp cocktail made with gin and lime juice, often sweetened with simple syrup or Rose’s lime juice.',

    //non-alcoholic cocktails
    'A luxurious, non-alcoholic syrup infused with the exotic flavor of saffron, perfect for adding a golden touch to beverages.',
    'A mocktail version of the classic Negroni, blending bitter non-alcoholic spirits with sweet vermouth and citrus for a sophisticated sip.',
    'A floral and tangy non-alcoholic cocktail that combines rose water, raspberry vinegar, and a touch of sweetness.',
    'A fun, slushy twist on the traditional Shirley Temple, blending ginger ale, grenadine, and orange juice into a frosty treat.',
    'A festive and bubbly mocktail that mimics the effervescence of champagne with a blend of sparkling water and citrus flavors.',
    'A sweet and spicy concoction featuring strawberries, a kick of chile, and the rich depth of balsamic vinegar.',
    'A tropical cooler that combines the sweetness of pineapple with the tangy depth of tamarind for a refreshing drink.',
    'A summer favorite, this thirst-quencher mixes fresh watermelon juice with zesty lime for a perfect balance of sweet and tart.',
    'A revitalizing drink packed with greens like cucumber and mint, offering a cool and hydrating experience.',
    'A chilled coffee-based beverage, often sweetened and blended with milk or cream, ideal for a caffeine kick on warm days.',
    'A non-alcoholic take on the classic sour, using the herbal aperitif Ghia for a complex and layered flavor profile.',
    'A vibrant and fruity mocktail that showcases the sweet and tart flavors of cherries, often mixed with lemonade or soda.',
    'A ‘green garden’ in a glass, this drink is a blend of vegetable juices and herbs, creating a nutritious and invigorating mocktail.',
    'Typically a bartender’s choice at the end of their shift, this could be any refreshing concoction to wind down after a busy night.',
    'An imaginative mocktail likely featuring a colorful mix of juices and syrups, evoking the whimsy of a vibrant garden party.',

    // DRINKS & MILSHAKES
    'A classic and popular cola-flavored soft drink with a distinctive taste and a refreshing fizz.',
    'A crisp, clear lemon-lime flavored soda that offers a burst of refreshment with its bubbly carbonation.',
    'A fruit-flavored carbonated soft drink that comes in a variety of flavors, with orange being the most iconic.',
    'A creamy and sweet blend of milk, strawberries, and ice cream, often topped with whipped cream.',
    'A smooth and rich drink made with ripe bananas, milk, and vanilla ice cream, creating a comforting flavor.',
    'A decadent and thick beverage combining chocolate syrup or cocoa with milk and chocolate ice cream.',
    'A simple yet delightful shake made with vanilla ice cream and milk, often garnished with a cherry on top.']